name: deployment
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get source
        uses: actions/checkout@v3

      - name: Use Node.js 
        uses: actions/setup-node@v2
        with:
          node-version: 18


      - name: install dependencies
        run: npm ci

      - name: Test code base
        run: npm run test

      - name: Build Code 
        run: npm run build


      - name: Deploy App
        run: | 
          echo "Deploying...."
          echo "{{ github.event }}"
