name: deployment
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        node-version: [10.x, 12.x, 14.x, 15.x]
    steps:
      - name: Get source
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}


      - name: install dependencies
        run: npm ci

      - name: Build Code 
        run: npm run build

      
      - name: Check Lint
        run: npm run lint


      - name: Test code base
        run: npm run test

      - name: Deploy App
        run: | 
          echo "Deploying...."
          echo "{{ github.event }}"
